Update rustic-compilation-panic regex
In a recent Rust upgrade, my panic messages in tests now have an
additional thread ID component after the initial `thread 'whatever'`
portion of the message, like in:

```
thread 'crate::module::submodule::tests::test' (294268) panicked at lib/rs/mylib/src/module.rs:1282:76:
```

This feature was added to rustc here: https://github.com/rust-lang/rust/pull/115746

This no longer matches the current regex for `rustic-compilation-panic`,
which expects nothing but a space between the module and the `"panicked"`.
That then breaks the "jump to failing test" functionality in test
compilation buffers.

To fix, I added a component to the regex that allows that value to be
optionally present. I also couldn't find any existing tests for the
regex, so I added a simple one. Not sure if it's in the right
location, or if it should be somewhere else. The test could be more
sophisticated: it doesn't validate that the appropriate groups are
present, just that the regex matches.